MY_CUSTOM_PERIPHERAL_VERSION = 1.0
MY_CUSTOM_PERIPHERAL_SITE = $(BR2_EXTERNAL_MY_CUSTOM_PERIPHERAL_PATH)
MY_CUSTOM_PERIPHERAL_SITE_METHOD = local


MY_CUSTOM_PERIPHERAL_LICENSE = GPL-2.0
MY_CUSTOM_PERIPHERAL_LICENSE_FILES = LICENSE

$(eval $(kernel-module))
$(eval $(generic-package))
