LINEAR_FUNCTION_ACCELERATOR_VERSION = 1.0
LINEAR_FUNCTION_ACCELERATOR_SITE = $(BR2_EXTERNAL_LINEAR_FUNCTION_ACCELERATOR_PATH)
LINEAR_FUNCTION_ACCELERATOR_SITE_METHOD = local


LINEAR_FUNCTION_ACCELERATOR_LICENSE = GPL-2.0
LINEAR_FUNCTION_ACCELERATOR_LICENSE_FILES = LICENSE

$(eval $(kernel-module))
$(eval $(generic-package))
